server.port=8080

# В Docker контейнере БД доступна на порту 5432 внутри сети
# Переменные окружения будут подставлены из docker-compose
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/network_dt}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.maximum-pool-size=10

logging.level.com.doppelganger=INFO
logging.level.org.springframework.web=WARN
spring.jackson.serialization.fail-on-empty-beans=false

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}